taskName: newTask1234
primaryResource:
gitProvider: deepak_git
artifactory: int_default_artifactory # rename if the artifactory integration is different
repoPath: creepy-pirate/jfrog-pipelines-task
mainBranch: main
protocol: https
buildOnCommit: True
publishOnCommit: False
